import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Ubuntu } from "next/font/google";
import ReactLenis from "lenis/react";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto=Ubuntu({
  weight:["400"],
  variable:"--font-roboto",
  subsets:["latin"]
})
import Navbar from "./_components/Navbar";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} w-full mx-auto antialiased`}
      >
        <div className="max-w-[100rem] w-full mx-auto font-roboto">
        <Navbar />
        <ReactLenis
        root
        options={{
          // Learn more -> https://github.com/darkroomengineering/lenis?tab=readme-ov-file#instance-settings
          lerp: 0.06,
          syncTouch:true
            
        }}
      >
       
       {children}
      </ReactLenis>
          
        </div>
      </body>
    </html>
  );
}
